Fix ASSERTION(!dsl_pool_sync_context(tx->tx_pool))
This assertion was observed during testing because the txg_sync
thread entered dmu_tx_assign() as part of synchronous memory reclaim.
To prevent this from happening the allocating in dbuf_dirty() was
changed to KM_PUSHPAGE which prevents direct reclaim.

  SPLError: 4281:0:(dmu_tx.c:1061:dmu_tx_assign())
  ASSERTION(!dsl_pool_sync_context(tx->tx_pool)) failed

  spl_debug_bug+0x81/0xe0 [spl]
  dmu_tx_assign+0x621/0x670 [zfs]
  zfs_inactive+0x160/0x2e0 [zfs]
  zpl_clear_inode+0xe/0x10 [zfs]
  clear_inode+0x87/0x100
  dispose_list+0x40/0x150
  prune_icache+0x193/0x2a0
  shrink_icache_memory+0x51/0x60
  shrink_slab+0x124/0x180
  do_try_to_free_pages+0x1bf/0x470
  try_to_free_pages+0x6b/0x70
  __alloc_pages_slowpath+0x2d8/0x5a0
  __alloc_pages_nodemask+0x19a/0x1f0
  alloc_pages_current+0x9a/0x100
  new_slab+0x225/0x2c0
  __slab_alloc+0x189/0x310
  __kmalloc+0x114/0x1c0
  kmem_alloc_debug+0x1fb/0x3a0 [spl]
  dbuf_dirty+0x249/0x14c0 [zfs]
  dmu_buf_will_dirty+0xa7/0x180 [zfs]
  dsl_dir_sync+0x43/0x220 [zfs]
  dsl_pool_sync+0x323/0x7c0 [zfs]
  spa_sync+0x3af/0xbb0 [zfs]
  txg_sync_thread+0x28b/0x4c0 [zfs]